examples:/suit_update: add non ethos option
future-proof-iot/RIOT pull request #4
Opened 2019-05-07 14:08 UTC by fjmolinas

### Contribution description

This PR adds the instructions for setting up updates within a wireless networks, therefore with some kind of border router between the node to update and the file-server. In this case the README suggests using gnrc_border_router.

### Testing procedure

on SAMR21 follow the readme

### Issues/PRs references

2019-05-07 14:08 UTC, fjmolinas commented
@emmanuelsearch Maybe you can test and verify this is understandable and accurate (the README).

2019-05-16 13:47 UTC, kaspar030 commented on examples/suit_update/README.md
> +A wireless node has no direct connection to th Internet we need to setup a border
```suggestion
A wireless node has no direct connection to the Internet we need to setup a border
```

2019-05-16 13:52 UTC, kaspar030 requested changes
some typos

2019-05-16 13:52 UTC, kaspar030 commented on examples/suit_update/README.md
> +router, to this use any node with a 802.15.4 radio and follow the instruction to
```suggestion
router, to this use any node with a 802.15.4 radio and follow the instructions to
```

2019-05-16 13:52 UTC, kaspar030 commented on examples/suit_update/README.md
> +In this scenario the node will be connected threw a border router so we flash the
```suggestion
In this scenario the node will be connected through a border router so we flash the
```

2019-05-16 13:52 UTC, kaspar030 commented on examples/suit_update/README.md
> +longer reachable threw its link local address but routed threw to border router
```suggestion
longer reachable through its link local address but routed through to border router
```

2019-05-20 12:46 UTC, fjmolinas commented
Closing to PR against suit-dev.

2019-05-20 12:46 UTC, closed without merging